networks:
  menuchi.net.back:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.name: "menuchi_bnet"
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24

volumes:
  postgres_data:
    name: postgres_data

services:
  menuchi.api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: menuchi.api:dev
    hostname: menuchi.api
    ports:
      - "8000:8000"
    env_file:
      - ./.docker/.dev.env
    depends_on:
      - menuchi.psql
    networks:
      menuchi.net.back:

  menuchi.psql:
    image: postgres:latest
    hostname: menuchi.psql
    container_name: menushi.psql
    env_file:
      - ./.docker/.dev.env
    environment:
      TZ: "Asia/Tehran"
      PGTZ: "Asia/Tehran"
      POSTGRES_DB: menuchi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      menuchi.net.back:
