name: Test and Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/menuchi
  REDIS_URL: redis://default@redis:6379/0
  OTP_REDIS_URL: redis://default@redis:6379/1
  OTP_STREAM: otps
  INTERNAL_OTP_URL: http://localhost:9000
  INTERNAL_OTP_ENDPOINT: /api/v1/get-otp
  S3_BUCKETNAME: c355966
  S3_ENDPOINT: http://parspack.net
  S3_ACCESSKEYID: cBM7deDXZobbbs5R
  S3_SECRETACCESSKEY: 3tLv0D1uvawRA9wjtdFCaLOQhrho9MxL
  S3_DEFAULT_KEY: c355966/default.jpg
  SESSION_SECRET: cABfwX3qaHsAPZ9gtIU7QxsKNqOrfhXM
  COOKIE_PRIVATE_KEY: WBruJAdkCnkC6TD8VaQkmd3JEIb95uts
  JWT_PRIVATE_KEY: yyirRpVwgDx7SkoiGM4CwiXmNjyRTQLF
  TRANSFORMERS_STREAM: images
  MENUCHI_FRONT_URL: "http://localhost:3000"
  
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:22-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: menuchi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update and Upgrade image
        run: apt-get update -y && apt-get upgrade -y && apt-get install -y openssl
        
      - name: Install Deps
        run: npm ci

      - name: Push DB with prisma
        run: npm run db-push

      - name: Test
        run: npm test
     
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mahdihaghverdi/menuchi-project:dev
        target: runtime
